### ISSUE TITLE
Download manager issues

### ISSUE THREAD

**Issue by lollox** [Emdek/otter#346]
In these days I'm testing Otter for more time so I'm finding more small problems

About the download manager, I don't know if it's inherited from webkit or is written from scratch, but on my Win7 system it works very bad... I tested it several times but for the most when I start a download it begins to download, but:

1. the speed is far away from the max available (always compared with other integrated download manager (Opera, Firefox) to be sure it's not a network/server problem);
2. it's really unstable (for example, begins at 200kbs, after few seconds is 15, then 50, 8, 100, 0, etc ... again always compared with other DM where all is more stable);
3. (above all) 9 out 10 times, the download is stopped before completation;
4. If I try to restart using the button, Otter crashes.

And, as special guest :P , here there is a feature request: can you copy the behavihor of Opera where if you click on the source address it's all selected automatically?

Tnx :)

**Comment by Emdek** [comment]
Since this ticket is silent I'm assuming that these issues do not happen anymore.
There was pretty big change there in 7a8d5d290606acf9108a02c5bf9685829f5dd1c3 which totally changed the way how does it work internally (needed to support upcoming downloads API of *QtWebEngine* and making it more friendly for concepts like Bittorent support: #59).

Please reopen if needed, as there might be new issues after that overhaul (so far it seems to be stable).
