### ISSUE TITLE
Differentiate between extract and copy

### ISSUE THREAD

**Issue by ersi-dnd** [Emdek/otter#639]
There's a function that I personally use extensively, even though it may seem uncommon. Otter right now allows this:

1. Select some text on webpage
2. Right-click
3. Select "Go to This Address"

It launches a search with the text string or goes to the address, if it's a proper url. (It's a bit buggy right now, because Shift+select should open up in new tab, but doesn't.)

What I'd like to see is that "Go to This Address" would open the text up in the secondary address field for viewing and editing. This is pretty important to me, so here it is once again:

1. Select some text on webpage
2. Right-click
3. Select the action, named for example "Edit (as) url"
4. The secondary address field would open up with the selection on it.

This action will be totally unique and absolutely worth it when it won't touch the clipboard. 

I know it's possible to make it work without touching the clipboard, because it already actually works like this. When we select some text, the browser knows what's selected, and "Go to This Address" goes there without touching the clipboard. My idea is to perform another action with the same selection - without touching the clipboard.

I would like a similar function for ordinary links. When we browse the web, we usually go on clicking links, and the click will take us there. I'd like to see a right-click menu action that would open up the url in the secondary address field, so as to take a closer look at the url and perhaps edit it before going there. There is a function like this in Elinks, and it works ideally because it does not touch the clipboard. 

Additionally, my idea is to create an Extract action, distinguished from Copy. Copy places the content to the clipboard, but Extract would make the content (url or selection) available for some next action, such as place to the secondary address field or into the search field or place into notes, without going via clipboard. Extract distinguished from Copy would make macros much more flexible.

**Comment by Emdek** [comment]
I'm afraid that it is too unique to be built-in (see #640).

BTW, the idea behind macros (maybe they need a better name) was to allow to write simple scripts to be executed when triggered, in this case it could be something like this:
```
var dialog = Environment.createDialog(Environment.Dialogs.OPENADDRESS);
dialog.setAddress(Environment.getActiveWindow().getActiveElement().getUrl());
dialog.show();
```
But since these APIs might overlap with these that already are semi-standard for extensions we need to wait before implementing this functionality.

It might be a good idea to collect such ideas in separate thread on forums (github is wrong place, wiki is more suitable, we can place these ideas there in future), so we would get some additional research data which would allow to design better API for scripting.

**Comment by ersi-dnd** [comment]
Aren't those scripts javascript? Because to me they look indistinguishable from javascript. Javascript is something I can barely read. I understand absolutely nothing about its background and syntax. Where do those names come from? What is the logic with the dots? The commands seem to be separated only by ";" which seems severely limiting and inflexible compared to Opera's "&", "|" and ">".  Opera's INI language is immediately understandable, but javascript I can still barely read after 15 years of trying to learn it. I don't understand how you can call it simple.

My suggestion was carefully thought out in order to avoid anything to do with javascript.

**Comment by Emdek** [comment]
@ersi-dnd, it's ECMAScript (basically JS without DOM) and uses the same syntax as C / C++ etc.
It's easy to learn and has the benefit of being actively used by millions of users worldwide.

> Javascript is something I can barely read. I understand absolutely nothing about its background and syntax. 

I can say the same about syntax from Opera. ;-)

The point of page with such ideas is to replace it later with snippets to be copy pasted into configuration dialog, no need to fully understand them to make use of them (just like no need to understand our C++ code which is even more complex).
We will decide how APIs will look like (at least these not covered by extensions) and we will have documentation for them. It is also possible to have editor (built-in or standalone) with syntax highlighting and code completion.

**Comment by ersi-dnd** [comment]
Opera's vocabulary (the list of commands) was easily read from inside the default ini files along with the syntax. Similarly, I thought Otter's files could use the list of commands, e.g. here https://github.com/Emdek/otter/blob/master/src/core/Action.cpp 
And users basically make sequences of those commands. This is how Opera worked. Everybody understood this. But where is ECMAscript's vocabulary coming from? 

The very idea that we don't need to understand it to use it is contrary to simplicity. I am a fairly good sampler (a sampler is the kind of coder between a total noob and an advanced hacker) and in some cases I am able to modify scripts to achieve what I want, but it's against the idea of simplicity when I don't understand how the script works. It will forever be trial and error, eternal frustration. I cannot modify it knowingly and creatively. In contrast, I knew pretty much everything Opera's commands could do in all imaginable combinations.

**Comment by Emdek** [comment]
@ersi-dnd, that doesn't differ much from what Opera offered, at least basic use cases.
But we will go for formalized syntax instead of inventing own language (as it doesn't make any sense).
But we need to define APIs.
Identifiers from *Action.h* will be reused of course, exposed as constants in ECMAScript environment, and use of basic actions without arguments could then look like:
```
Environment.triggerAction(Environment.Actions.OpenSelectionAsLink);
Environment.triggerAction(Environment.Actions.CopyImageToClipboard);
```
It's direct equivalent to how we do it in source code:
```
ActionsManager::triggerAction(Action::OpenSelectionAsLinkAction, this);
ActionsManager::triggerAction(Action::CopyImageToClipboardAction, this);
```
``Environment`` (name not final yet) would be used as namespace, to avoid conflicts, we could just define names directly but that would be bad.
It's really simple to work with but requires additional knowledge for more advanced usage, like loops, conditions etc. But it's not required to make use of it.
