### ISSUE TITLE
slow rendering of certain pages (weekly 56)

### ISSUE THREAD

**Issue by codespotx** [Emdek/otter#686]
some pages are rendered with ridiculous speed.
e.g:
open https://github.com/Emdek/otter/blob/master/3rdparty/mousegestures/MouseGestures.cpp
focus window
press cursor "down" key and wait for page to refresh (takes approx. 1s with 32bit, even slower with 64bit).
Same test with chrome shows no delay (i.e. few milliseconds).

testing environment: otter weekly 56 (32 and 64 bit), windows 7 64, QT 5.4.0

**Comment by Emdek** [comment]
That's known deficiency of QtWebKit (WebKit1 in general), try QtWebEngine backend instead, see #615.

**Comment by Frenzie** [comment]
That's a QtWebKit bug, fixed in the upcoming Qt 5.5 (and QtWebEngine). See https://bugreports.qt.io/browse/QTBUG-40559

**Comment by Emdek** [comment]
@Frenzie, heh, while WebKit is slow on itself there are other bottlenecks too. :-D

**Comment by codespotx** [comment]
@Emdek thanks for the quick response.
still, even if it is a QT but I don't consider this issue as "resolved" until the according QT update is performed ("non experimental").

**Comment by Emdek** [comment]
@codespotx, sure, but I would prefer wiki page with list of known upstream issues instead of keeping them open and forgetting to close when fixed upstream. :-)
Also, such approach only applies to Windows and MacOS, where Qt has to be bundled anyway, as so far we depend on system wide packages elsewhere.
Such wiki page would be best, so I've finally added it now. :-)
https://github.com/Emdek/otter/wiki/Upstream-Bugs

**Comment by codespotx** [comment]
@Emdek thank you for this clarification :-)
